<?php
require_once __DIR__ . '/db.php';
require_once __DIR__ . '/functions.php';

function hope_pairing_json(array $data, int $code = 200): void { http_response_code($code); header('Content-Type: application/json; charset=utf-8'); echo json_encode($data, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
function hope_pairing_ok(array $data=[]): void { hope_pairing_json(array_merge(['ok'=>true], $data)); }
function hope_pairing_err(string $message, int $code=400, array $extra=[]): void { hope_pairing_json(array_merge(['ok'=>false,'message'=>$message],$extra),$code); }
function hope_pairing_input(): array { $raw=file_get_contents('php://input')?:''; $j=json_decode($raw,true); return is_array($j)?$j:($_POST?:[]); }
function hope_normalize_url(string $url): string { $url=trim($url); $url=preg_replace('~\s+~','',$url) ?: $url; if($url!=='' && !preg_match('~^https?://~i',$url)) $url='https://'.$url; return rtrim($url,'/'); }
function hope_request_code(string $prefix='HOPE'): string { return $prefix.'-'.date('Ymd-His').'-'.strtoupper(bin2hex(random_bytes(3))); }
function hope_secret(): string { return bin2hex(random_bytes(32)); }
function hope_bearer_token(): string { $h=$_SERVER['HTTP_AUTHORIZATION'] ?? $_SERVER['REDIRECT_HTTP_AUTHORIZATION'] ?? ''; if($h==='' && function_exists('apache_request_headers')){ foreach(apache_request_headers() as $k=>$v){ if(strtolower((string)$k)==='authorization'){ $h=(string)$v; break; } } } return preg_match('/^Bearer\s+(.+)$/i',trim($h),$m)?trim($m[1]):''; }
function hope_remote_json(string $baseUrl,string $path,array $payload=[],string $method='POST',string $token='',int $timeout=18): array { $url=hope_normalize_url($baseUrl).'/'.ltrim($path,'/'); if($method==='GET' && $payload) $url.=(str_contains($url,'?')?'&':'?').http_build_query($payload); $headers=['Accept: application/json','Content-Type: application/json','User-Agent: HOPe-Pairing/1.0']; if($token!=='') $headers[]='Authorization: Bearer '.$token; $ch=curl_init($url); curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>$timeout,CURLOPT_CONNECTTIMEOUT=>8,CURLOPT_HTTPHEADER=>$headers,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_MAXREDIRS=>3]); if($method!=='GET'){ curl_setopt($ch,CURLOPT_CUSTOMREQUEST,$method); curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)); } $body=curl_exec($ch); $err=curl_error($ch); $code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE); curl_close($ch); $json=is_string($body)?json_decode($body,true):null; if(!is_array($json)) $json=['ok'=>false,'message'=>$err!==''?$err:'Respons bukan JSON','raw'=>(string)$body]; $json['_http_code']=$code; $json['_error']=$err; return $json; }
function ensure_hope_integration_schema(): void { static $done=false; if($done) return; $done=true; $pdo=db(); $pdo->exec("CREATE TABLE IF NOT EXISTS api_pairing_requests (id BIGINT AUTO_INCREMENT PRIMARY KEY, direction VARCHAR(20) NOT NULL DEFAULT 'incoming', request_code VARCHAR(90) NOT NULL, request_secret_hash VARCHAR(255) NULL, requester_name VARCHAR(180) NOT NULL, requester_type VARCHAR(50) NOT NULL, requester_base_url VARCHAR(255) NOT NULL, target_name VARCHAR(180) NULL, target_type VARCHAR(50) NOT NULL, target_base_url VARCHAR(255) NULL, requested_scope VARCHAR(80) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pending', callback_url VARCHAR(255) NULL, access_token_plain TEXT NULL, token_hash VARCHAR(255) NULL, reject_reason TEXT NULL, approved_by BIGINT NULL, approved_at DATETIME NULL, rejected_by BIGINT NULL, rejected_at DATETIME NULL, expires_at DATETIME NULL, last_checked_at DATETIME NULL, last_message TEXT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP, notification_dismissed_at DATETIME NULL, notification_dismissed_by BIGINT NULL, UNIQUE KEY uq_api_pairing_code (request_code), KEY idx_api_pairing_status (status), KEY idx_api_pairing_direction (direction)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); $pdo->exec("CREATE TABLE IF NOT EXISTS api_connections (id BIGINT AUTO_INCREMENT PRIMARY KEY, connection_name VARCHAR(180) NOT NULL, connection_type VARCHAR(50) NOT NULL, remote_system_type VARCHAR(50) NOT NULL, remote_base_url VARCHAR(255) NOT NULL, access_scope VARCHAR(80) NOT NULL, token_hash VARCHAR(255) NULL, access_token_plain TEXT NULL, status VARCHAR(30) NOT NULL DEFAULT 'active', paired_from_request_code VARCHAR(90) NULL, paired_by BIGINT NULL, paired_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, revoked_by BIGINT NULL, revoked_at DATETIME NULL, last_used_at DATETIME NULL, last_test_at DATETIME NULL, last_test_status VARCHAR(30) NULL, last_test_message TEXT NULL, notes TEXT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP, KEY idx_api_connections_status (status), KEY idx_api_connections_remote_type (remote_system_type)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); $pdo->exec("CREATE TABLE IF NOT EXISTS integration_stock_transfers (id BIGINT AUTO_INCREMENT PRIMARY KEY, transfer_no VARCHAR(80) NOT NULL, source_system VARCHAR(60) NOT NULL DEFAULT 'dapur', source_base_url VARCHAR(255) NULL, payload_hash CHAR(64) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'posted', notes TEXT NULL, created_by_connection_id BIGINT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, cancelled_by INT NULL, cancelled_at DATETIME NULL, cancel_note TEXT NULL, UNIQUE KEY uq_transfer_no_source (transfer_no, source_system), UNIQUE KEY uq_transfer_payload (payload_hash), KEY idx_transfer_status (status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); }
function hope_pairing_scope_for(string $requesterType,string $targetType='hope'): string { $r=strtolower($requesterType); if($r==='dapur') return 'dapur_stock_sender'; return 'readonly'; }
function hope_pairing_auth(string $need=''): array { ensure_hope_integration_schema(); $token=hope_bearer_token(); if($token==='' || strlen($token)<20) hope_pairing_err('Token kosong/tidak valid.',401); $hash=hash('sha256',$token); $st=db()->prepare("SELECT * FROM api_connections WHERE status='active' AND token_hash=? ORDER BY id DESC LIMIT 1"); $st->execute([$hash]); $row=$st->fetch(PDO::FETCH_ASSOC); if(!$row) hope_pairing_err('Token tidak dikenal.',401); if($need==='stock_transfer.write' && !in_array($row['access_scope'],['dapur_stock_sender','admin_rw','superadmin'],true)) hope_pairing_err('Scope koneksi tidak cukup.',403); db()->prepare('UPDATE api_connections SET last_used_at=NOW() WHERE id=?')->execute([(int)$row['id']]); return $row; }
?>
