<?php
require_once __DIR__ . '/../core/auth.php'; require_once __DIR__ . '/../core/csrf.php'; require_once __DIR__ . '/../core/security.php'; require_once __DIR__ . '/../core/permissions.php'; require_once __DIR__ . '/../core/api_pairing.php';
start_secure_session(); require_admin(); csrf_check(); ensure_hope_integration_schema(); $u=current_user()??[]; $act=(string)($_POST['act']??'');
try{
 if($act==='create_request'){ $base=hope_normalize_url((string)($_POST['base_url']??'')); if($base==='') throw new Exception('Website Dapur wajib diisi.'); $code=hope_request_code('HOPE2DAPUR'); $secret=hope_secret(); $secretHash=password_hash($secret,PASSWORD_DEFAULT); $payload=['request_code'=>$code,'request_secret_hash'=>$secretHash,'requester_name'=>'HOPe POS System','requester_type'=>'hope','requester_base_url'=>base_url(''),'target_type'=>'dapur','callback_url'=>base_url('api/pairing/status.php')]; $res=hope_remote_json($base,'api/pairing/request.php',$payload,'POST'); $status=!empty($res['ok'])?'pending':'failed'; db()->prepare("INSERT INTO api_pairing_requests(direction,request_code,request_secret_hash,requester_name,requester_type,requester_base_url,target_name,target_type,target_base_url,requested_scope,status,callback_url,last_message,created_at) VALUES('outgoing',?,?,?,?,?,?,?,?,?,?,?,NOW())")->execute([$code,$secretHash,'HOPe POS System','hope',base_url(''),'Dapur','dapur',$base,'dapur_stock_sender',$status,base_url('api/pairing/status.php'),(string)($res['message']??'')]); }
 elseif($act==='approve'){ if(!current_user_is_owner()) throw new Exception('Hanya owner yang dapat approve koneksi.'); $id=(int)($_POST['id']??0); $r=db()->prepare("SELECT * FROM api_pairing_requests WHERE id=? AND direction='incoming' LIMIT 1"); $r->execute([$id]); $req=$r->fetch(PDO::FETCH_ASSOC); if(!$req) throw new Exception('Request tidak ditemukan.'); $token='hope_'.bin2hex(random_bytes(32)); db()->prepare("UPDATE api_pairing_requests SET status='approved', access_token_plain=?, token_hash=?, approved_by=?, approved_at=NOW(), last_message='Approved', updated_at=NOW() WHERE id=?")->execute([$token,hash('sha256',$token),(int)($u['id']??0),$id]); db()->prepare("INSERT INTO api_connections(connection_name,connection_type,remote_system_type,remote_base_url,access_scope,token_hash,access_token_plain,status,paired_from_request_code,paired_by,paired_at) VALUES(?,?,?,?,?,?,?,?,?,?,NOW())")->execute([(string)$req['requester_name'],'incoming',(string)$req['requester_type'],(string)$req['requester_base_url'],(string)$req['requested_scope'],hash('sha256',$token),$token,'active',(string)$req['request_code'],(int)($u['id']??0)]); }
 elseif($act==='reject'){ if(!current_user_is_owner()) throw new Exception('Hanya owner yang dapat reject koneksi.'); db()->prepare("UPDATE api_pairing_requests SET status='rejected', reject_reason=?, rejected_by=?, rejected_at=NOW(), updated_at=NOW() WHERE id=? AND direction='incoming'")->execute([trim((string)($_POST['reason']??'Ditolak')),(int)($u['id']??0),(int)($_POST['id']??0)]); }
 elseif($act==='check_status'){ $id=(int)($_POST['id']??0); $st=db()->prepare("SELECT * FROM api_pairing_requests WHERE id=? AND direction='outgoing' LIMIT 1"); $st->execute([$id]); $r=$st->fetch(PDO::FETCH_ASSOC); if(!$r) throw new Exception('Request keluar tidak ditemukan.'); $secret=(string)($_POST['request_secret']??''); $res=hope_remote_json((string)$r['target_base_url'],'api/pairing/status.php',['request_code'=>(string)$r['request_code'],'request_secret'=>$secret],'GET'); if(!empty($res['ok']) && ($res['status']??'')==='approved' && !empty($res['access_token'])){ $token=(string)$res['access_token']; db()->prepare("UPDATE api_pairing_requests SET status='approved', access_token_plain=?, token_hash=?, last_checked_at=NOW(), last_message='Approved', updated_at=NOW() WHERE id=?")->execute([$token,hash('sha256',$token),$id]); db()->prepare("INSERT INTO api_connections(connection_name,connection_type,remote_system_type,remote_base_url,access_scope,token_hash,access_token_plain,status,paired_from_request_code,paired_by,paired_at) VALUES(?,?,?,?,?,?,?,?,?,?,NOW())")->execute([(string)($r['target_name']?:'Dapur'),'outgoing','dapur',(string)$r['target_base_url'],(string)($res['access_scope']??'dapur_stock_sender'),hash('sha256',$token),$token,'active',(string)$r['request_code'],(int)($u['id']??0)]); } else { db()->prepare("UPDATE api_pairing_requests SET status=?, last_checked_at=NOW(), last_message=?, updated_at=NOW() WHERE id=?")->execute([(string)($res['status']??'pending'),(string)($res['message']??''),$id]); } }
}catch(Throwable $e){ set_setting('last_integration_error',$e->getMessage()); }
redirect(base_url('admin/dapur_connection.php'));
