<?php
require_once __DIR__ . '/../core/auth.php';
require_once __DIR__ . '/../core/csrf.php';
require_once __DIR__ . '/../core/security.php';
require_once __DIR__ . '/../core/permissions.php';
require_once __DIR__ . '/../core/api_pairing.php';
start_secure_session(); require_admin(); ensure_hope_integration_schema();
$customCss=setting('custom_css','');
$incoming=db()->query("SELECT * FROM api_pairing_requests WHERE direction='incoming' ORDER BY id DESC LIMIT 50")->fetchAll(PDO::FETCH_ASSOC);
$outgoing=db()->query("SELECT * FROM api_pairing_requests WHERE direction='outgoing' ORDER BY id DESC LIMIT 50")->fetchAll(PDO::FETCH_ASSOC);
$conns=db()->query("SELECT * FROM api_connections ORDER BY id DESC LIMIT 80")->fetchAll(PDO::FETCH_ASSOC);
$logs=hope_pairing_table_exists('api_logs')?db()->query("SELECT * FROM api_logs ORDER BY id DESC LIMIT 12")->fetchAll(PDO::FETCH_ASSOC):[];
$lastErr=setting('last_integration_error',''); set_setting('last_integration_error','');
function hb($s){ $s=(string)$s; $cls=in_array($s,['active','approved','ok','posted','dry_run_ok'],true)?'ok':($s==='pending'?'warn':'danger'); return '<span class="badge '.$cls.'">'.e($s).'</span>'; }
function smallbtn($act,$id,$label,$class='light',$confirm=''){
  $c=$confirm!==''?' onsubmit="return confirm(&quot;'.e($confirm).'&quot;)"':'';
  return '<form method="post" action="api_pairing_action.php" style="display:inline"'.$c.'><input type="hidden" name="_csrf" value="'.e(csrf_token()).'"><input type="hidden" name="act" value="'.e($act).'"><input type="hidden" name="id" value="'.(int)$id.'"><button class="btn '.$class.'" type="submit">'.e($label).'</button></form>';
}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Koneksi ke Dapur</title><link rel="icon" href="<?php echo e(favicon_url()); ?>"><link rel="stylesheet" href="<?php echo e(asset_url('assets/app.css')); ?>"><style><?php echo $customCss; ?>.compact-admin{font-size:13px}.compact-admin .table th,.compact-admin .table td{padding:7px 8px;vertical-align:top}.compact-admin input,.compact-admin select{min-height:34px;padding:6px 8px;font-size:13px}.compact-admin .btn{padding:7px 10px;font-size:13px}.compact-grid{display:grid;grid-template-columns:1.2fr .8fr;gap:12px}.mini-actions{display:flex;flex-wrap:wrap;gap:6px}.log-pre{white-space:pre-wrap;max-width:720px;max-height:220px;overflow:auto;font-size:12px}.status-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#9ca3af;margin-right:5px}.badge.ok .status-dot{background:#16a34a}@media(max-width:900px){.compact-grid{grid-template-columns:1fr}}</style></head><body><div class="container"><?php include __DIR__.'/partials_sidebar.php'; ?><div class="main"><div class="topbar"><button class="btn" data-toggle-sidebar type="button">Menu</button><div class="title">Koneksi ke Dapur</div><div class="spacer"></div><a class="btn" href="<?php echo e(base_url('admin/api_error_log.php')); ?>">Error Log API</a></div><div class="content compact-admin">
<?php if($lastErr): ?><div class="card" style="border-color:#bfdbfe;background:#eff6ff;color:#1e3a8a"><?php echo e($lastErr); ?></div><?php endif; ?>
<div class="compact-grid"><div class="card"><h3>Hubungkan HOPe ke Dapur</h3><p class="muted">Isi website Dapur saja. Setelah di-approve di Dapur, klik <b>Cek Status</b>. Secret pairing disimpan otomatis, jadi tidak ada input token manual.</p><form method="post" action="api_pairing_action.php" class="grid cols-3"><input type="hidden" name="_csrf" value="<?php echo e(csrf_token()); ?>"><input type="hidden" name="act" value="create_request"><div class="row"><label>Website Dapur</label><input name="base_url" placeholder="https://dapur.domain.com" required></div><div class="row" style="align-self:end"><button class="btn">Hubungkan</button></div></form></div><div class="card"><h3>Panel Test Cepat</h3><p class="muted">Gunakan tombol test di tabel koneksi. Semua test transfer memakai <b>dry-run</b>, tidak membuat transaksi dan tidak mengubah stok.</p><a class="btn light" href="<?php echo e(base_url('admin/api_error_log.php')); ?>">Lihat Error Log</a></div></div>
<div class="card"><h3>Koneksi Aktif</h3><table class="table"><tr><th>Nama</th><th>Remote</th><th>Scope</th><th>Status</th><th>Terakhir Test</th><th>Aksi</th></tr><?php foreach($conns as $c): ?><tr><td><?php echo e($c['connection_name']); ?><br><small><?php echo e($c['connection_type'].' / '.$c['remote_system_type']); ?></small></td><td><?php echo e($c['remote_base_url']); ?></td><td><?php echo e($c['access_scope']); ?></td><td><?php echo hb($c['status']); ?></td><td><?php echo e($c['last_test_at']??'-'); ?><br><small><?php echo e($c['last_test_message']??''); ?></small></td><td><div class="mini-actions"><?php if(($c['connection_type']??'')==='outgoing'): ?><?php echo smallbtn('test_connection',(int)$c['id'],'Tes Koneksi'); ?><?php endif; ?><?php if(($c['connection_type']??'')==='incoming' && (($c['remote_system_type']??'')==='dapur' || ($c['connection_type']??'')==='incoming')): ?><?php echo smallbtn('test_receive_transfer',(int)$c['id'],'Tes Terima Stok'); ?><?php endif; ?><?php if(current_user_is_owner()): ?><?php echo smallbtn('revoke_connection',(int)$c['id'],'Hapus/Revoke','danger','Cabut koneksi ini? Token tidak bisa dipakai lagi.'); ?><?php endif; ?></div></td></tr><?php endforeach; if(!$conns): ?><tr><td colspan="6" class="muted">Belum ada koneksi aktif.</td></tr><?php endif; ?></table></div>
<div class="card"><h3>Request Keluar ke Dapur</h3><table class="table"><tr><th>Waktu</th><th>URL Dapur</th><th>Status</th><th>Pesan</th><th>Aksi</th></tr><?php foreach($outgoing as $r): ?><tr><td><?php echo e($r['created_at']); ?></td><td><?php echo e($r['target_base_url']); ?></td><td><?php echo hb($r['status']); ?></td><td><?php echo e($r['last_message']); ?></td><td><div class="mini-actions"><?php echo smallbtn('check_status',(int)$r['id'],'Cek Status'); ?><?php echo smallbtn('delete_request',(int)$r['id'],'Hapus Request','danger','Hapus request pairing ini?'); ?></div></td></tr><?php endforeach; if(!$outgoing): ?><tr><td colspan="5" class="muted">Belum ada request keluar.</td></tr><?php endif; ?></table></div>
<div class="card"><h3>Request Masuk dari Dapur</h3><table class="table"><tr><th>Waktu</th><th>Peminta</th><th>URL</th><th>Scope</th><th>Status</th><th>Aksi</th></tr><?php foreach($incoming as $r): ?><tr><td><?php echo e($r['created_at']); ?></td><td><?php echo e($r['requester_name']); ?></td><td><?php echo e($r['requester_base_url']); ?></td><td><?php echo e($r['requested_scope']); ?></td><td><?php echo hb($r['status']); ?></td><td><div class="mini-actions"><?php if($r['status']==='pending' && current_user_is_owner()): ?><?php echo smallbtn('approve',(int)$r['id'],'Approve'); ?><?php echo smallbtn('reject',(int)$r['id'],'Reject','danger'); ?><?php endif; ?><?php echo smallbtn('delete_request',(int)$r['id'],'Hapus','danger','Hapus request ini?'); ?></div></td></tr><?php endforeach; if(!$incoming): ?><tr><td colspan="6" class="muted">Belum ada request masuk.</td></tr><?php endif; ?></table></div>
<div class="card"><h3>Log API Terakhir</h3><table class="table"><tr><th>Waktu</th><th>Arah</th><th>Endpoint</th><th>Status</th><th>Pesan</th></tr><?php foreach($logs as $l): ?><tr><td><?php echo e($l['created_at']); ?></td><td><?php echo e($l['direction']); ?></td><td><?php echo e($l['endpoint']); ?></td><td><?php echo hb($l['status']); ?></td><td><?php echo e($l['message']); ?></td></tr><?php endforeach; if(!$logs): ?><tr><td colspan="5" class="muted">Belum ada log.</td></tr><?php endif; ?></table></div>
</div></div></div><script defer src="<?php echo e(asset_url('assets/app.js')); ?>"></script></body></html>
